GraSP:
  exp_name: "incre_fc_95_stp"
  network: fc
  depth: 2
  dataset: mnist
  batch_size: 128
  epoch: 10
  learning_rate: 0.001
  weight_decay: 1e-4
  exception: -1
  iterations: 1
  normalize: false
  target_ratio: 0.95
  pruner: GraSP
  pruner_file: GraSP_zo_mask
  num_classes: 10
  samples_per_class: 10
  samples_batches: 5
  num_iters: 1

optimizer:
  name: ZO_SCD_mask
  grad_estimator: STP
  grad_sparsity: 0
  STP:  True
  patience_table: False

scheduler:
  name: 'PresetLRScheduler'
  gamma: 0.985
  lr_schedule: {0: 1,
                2: 0.1,
                5: 0.01}

pretrained:
  incre: True
  load_model_path: './runs/pruning/mnist/fc/ADAM/fc_95_FO_adam/20230308-083304/run_None/finetune_mnist_fc2_r0.95_it0_best.pth.tar'
  pruned: True

run:
  runs: None
  n_epochs: 100
  batch_size: 32
  use_cuda: 1
  gpu_id: 0
  deterministic: 1
  log_interval: 200
  train_noise: 0

model:
  tensorized: 0
  uncompressed: 0
  precondition: 0

checkpoint:
  save_model: "model/MNIST_notensor_SCD"
  save_mode: "best"
  proj_share_weight: 1
  label_smoothing: 1
